# Generated by Django 4.0.6 on 2022-07-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='description',
            field=models.CharField(default='Orden', max_length=255),
        ),
    ]
