# Generated by Django 4.0.6 on 2022-07-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
