# Generated by Django 4.0.6 on 2022-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_orden_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivoentrada',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monitor',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
