# Generated by Django 4.0.6 on 2022-07-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_dispositivoentrada_stock_monitor_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadora',
            name='orden',
        ),
        migrations.AddField(
            model_name='computadora',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='computadoras',
            field=models.ManyToManyField(to='computer.computadora'),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computer.monitor'),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='raton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computer.raton'),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='teclado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computer.teclado'),
        ),
    ]
